apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace/vms-namespace.yaml
  - operator/hyperconverged.yaml
  - templates/vm-from-template.yaml
  - templates/rhel8-vm-01.yaml
