# This is the Edge TLS piece — HAProxy terminates HTTPS
# then forwards HTTP to Istio ingressgateway
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: bookinfo
  namespace: istio-system
spec:
  host: bookinfo.apps.ocp4.ocplab.online
  port:
    targetPort: 8080
  tls:
    termination: edge               # ← HAProxy handles TLS
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: istio-ingressgateway      # ← Points to Istio, not the app
    weight: 100
