apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rhel9-gitops-vm
  namespace: vms
  labels:
    app: rhel9-gitops-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: rhel9-gitops-vm
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 2
          threads: 1
        memory:
          guest: 4Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
              bootOrder: 1
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
          rng: {}
      networks:
        - name: default
          pod: {}
      evictionStrategy: LiveMigrate
      volumes:
        - name: rootdisk
          dataVolume:
            name: rhel9-gitops-vm-rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: cloud-user
              password: redhat123
              chpasswd:
                expire: false
      terminationGracePeriodSeconds: 180
  dataVolumeTemplates:
    - metadata:
        name: rhel9-gitops-vm-rootdisk
      spec:
        storage:
          storageClassName: ocs-storagecluster-ceph-rbd-virtualization
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 30Gi
        source:
          snapshot:                               # ← changed from pvc to snapshot
            namespace: openshift-virtualization-os-images
            name: rhel9-ab4ec16077fe             # ← the VolumeSnapshot we confirmed
