apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp-virt
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/KadirSoft/gitops-ocp
    targetRevision: main
    path: virt
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-cnv
  ignoreDifferences:
    - group: kubevirt.io
      kind: VirtualMachine
      jsonPointers:
        - /spec/template/spec/domain/devices/interfaces/0/macAddress
        - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
